# Generated by Django 4.2.7 on 2024-01-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers_Dgree',
            new_name='Teachers_Degree',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='dgree',
            new_name='degree',
        ),
    ]
