# Generated by Django 4.2.7 on 2024-01-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='degree',
        ),
        migrations.DeleteModel(
            name='Teachers_Degree',
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
