# Generated by Django 4.2.7 on 2024-01-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_degree_delete_teachers_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituition', models.CharField(max_length=60)),
                ('background_medium', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('qualification', models.CharField(max_length=60)),
                ('present_location', models.CharField(max_length=60)),
                ('permanent_address', models.CharField(max_length=60)),
                ('preferred_classes', models.CharField(max_length=60)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
