# Generated by Django 4.2.7 on 2024-01-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_alter_teacher_image'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='turion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('complete', 'complete')], default='pending', max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.subject')),
            ],
        ),
    ]
