# Generated by Django 4.2.7 on 2024-01-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turion',
            name='fee',
        ),
        migrations.AddField(
            model_name='subject',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
