# Generated by Django 4.2.7 on 2024-01-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_student_class'),
        ('tuition', '0002_remove_turion_fee_subject_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyTuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('complete', 'complete')], default='pending', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentclass'),
        ),
        migrations.DeleteModel(
            name='turion',
        ),
    ]
