# Generated by Django 4.2.7 on 2024-01-17 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuition', '0003_applytuition_alter_subject_name_delete_turion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytuition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
