# Generated by Django 4.2.7 on 2024-01-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_degree_delete_teachers_degree_and_more'),
        ('student', '0004_alter_student_user'),
        ('tuition', '0004_alter_applytuition_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.CreateModel(
            name='TuitionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_name', models.ManyToManyField(to='student.studentclass')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition.tuitionsubject'),
        ),
    ]
