# Generated by Django 4.2.7 on 2024-01-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_degree_delete_teachers_degree_and_more'),
        ('student', '0004_alter_student_user'),
        ('tuition', '0005_alter_subject_teacher_tuitionsubject_subject_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Tuition',
        ),
        migrations.RemoveField(
            model_name='tuitionsubject',
            name='class_name',
        ),
    ]
