# Generated by Django 4.2.7 on 2024-01-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_degree_delete_teachers_degree_and_more'),
        ('tuition', '0007_applytuition_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
