# Generated by Django 4.2.7 on 2024-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0008_tuitionsubject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
