# Generated by Django 4.2.7 on 2024-01-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentclass_alter_student_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
    ]
